// Code generated by build.go. DO NOT EDIT.
package configs

import (
	"svc-dynamic-form-go/src/controllers"
	"svc-dynamic-form-go/src/repositories"
	"svc-dynamic-form-go/src/services"
)

type RouteOptions struct {
	// REGISTER CONTROLLERS BELLOW
	OrganizationController *controllers.OrganizationController
	PublicationController *controllers.PublicationController
	UserController *controllers.UserController

}

func Build() RouteOptions {
	// INSTANTIATE REPOSITORIES, SERVICES, AND CONTROLLERS BELLOW
	organizationRepository := repositories.NewOrganizationRepository(DB)
	publicationRepository := repositories.NewPublicationRepository(DB)
	userRepository := repositories.NewUserRepository(DB)
	organizationService := services.NewOrganizationService(organizationRepository)
	publicationService := services.NewPublicationService(publicationRepository)
	userService := services.NewUserService(userRepository)
	organizationController := controllers.NewOrganizationController(organizationService, userService)
	publicationController := controllers.NewPublicationController(publicationService)
	userController := controllers.NewUserController(userService)

	return RouteOptions{
		// REGISTER THE INSTANCES OF CONTROLLERS BELLOW
		OrganizationController: organizationController,
		PublicationController: publicationController,
		UserController: userController,

	}

}

